### ISSUE TITLE
Add for-user-id param for getCharge

### ISSUE THREAD

**Issue by melissa-nextpay** [xendit/xendit-node#101]
Need a way to specify sub-account ID for xenPlatform users when using this endpoint: [https://github.com/xendit/xendit-node#get-charge](url). Refer to: [https://developers.xendit.co/api-reference/#get-charge](url)
Example:
`card.getCharge(data: { chargeID: string; forUserID?: string })`

**Comment by stanleynguyen** [comment]
Hey @melissa-nextpay , this feature has been released in [v1.14.0](https://github.com/xendit/xendit-node/releases/tag/v1.14.0)

**Comment by melissa-nextpay** [comment]
Oh. Awesome, thank you!
