### ISSUE TITLE
Support EWALLET tokenization

### ISSUE THREAD

**Issue by anthonyballugjr** [xendit/xendit-node#106]
The API also supports tokenization of e-wallets. it would be great if the SDK supports it too.
[https://developers.xendit.co/api-reference/#ewallets](https://developers.xendit.co/api-reference/#ewallets)

Related issue: #107

**Comment by luminto17** [comment]
Hi @anthonyballugjr , we have just released ewallet tokenization support in v1.19.4 https://github.com/xendit/xendit-node/releases/tag/v1.19.4

Kindly check it out and let us know if any feedback. Thanks for the recommendation!
