### ISSUE TITLE
Link account tokenization as a separate service

### ISSUE THREAD

**Issue by anthonyballugjr** [xendit/xendit-node#107]
It seems that that creating a link account token uses the same endpoint for both DIRECT DEBIT and EWALLET but treated in the docs and this SDK as exclusive for DIRECT DEBIT only.

[https://developers.xendit.co/api-reference/#initialize-linked-account-tokenization](https://developers.xendit.co/api-reference/#initialize-linked-account-tokenization)
[https://developers.xendit.co/api-reference/#tokenized-account-linking](https://developers.xendit.co/api-reference/#tokenized-account-linking)

P.S.: if not possible, maybe support EWALLET account tokenization "properties" also to DIRECT_DEBIT params
![image](https://user-images.githubusercontent.com/40159033/131054957-96855022-60ab-4cd3-b05b-91ed58382f84.png)
**props for EWALLET also?**

Related issue: #106

**Comment by luminto17** [comment]
Hi @anthonyballugjr , we have just released an improvement related to this issue in v1.19.4 https://github.com/xendit/xendit-node/releases/tag/v1.19.4

Kindly check it out and let us know if any feedback. Thanks for the recommendation!
