### ISSUE TITLE
Add with-fee-rule header on createInvoice

### ISSUE THREAD

**Issue by anthonyballugjr** [xendit/xendit-node#110]
![image](https://user-images.githubusercontent.com/40159033/132466547-99035e5f-ca43-4944-a3a9-efd2b81eafe5.png)
![image](https://user-images.githubusercontent.com/40159033/132466624-2c5487b8-6dfa-48bf-8fb0-e16f3d9a83ae.png)

**Comment by luminto17** [comment]
Hi @anthonyballugjr , we have released your request in this v1.19.2 https://github.com/xendit/xendit-node/releases/tag/v1.19.2. Kindly check it out when you have the chance
