### ISSUE TITLE
Tidak bisa memilih metode pembayaran

### ISSUE THREAD

**Issue by hakimasmui** [xendit/xendit-node#112]
Saya ingin bertanya terkait API node js, dimana saya tidak bisa customize metode pembayaran melalui API. Dari kode saya dibawah ini ketika saya membuka response invoice_url nya, tetap harus memilih metode pembayarannya.

var parameter = {
		externalID:external_id,
		amount:amount,
		invoiceDuration:3600,
		payment_methods:arrMetode,
		items:item_details
	}
	
	i.createInvoice(parameter)
	.then(async (r) => {
		console.log(r);

		let result = {
			token: r.id,
			redirect_url: r.invoice_url
		}
		return resolve(result);
	});

**Comment by luminto17** [comment]
Selamat siang @hakimasmui , apakah bisa dibantu untuk melampirkan pesan kesalahan atau respon nya? 

Untuk customization metode pembayaran dapat dilakukan dengan melampirkan kode payment method yang hendak digunakan ya https://developers.xendit.co/api-reference/id/#pembuatan-invoice
![Screen Shot 2021-09-27 at 12 26 43](https://user-images.githubusercontent.com/9628847/134849823-fc32644a-9618-4cd1-a229-80e6125b231a.png)

Semoga membantu

**Comment by hakimasmui** [comment]
Dear Tim Xendit.

Terima kasih atas balasannya. Disini saya sudah bisa sampai membuat
Invoice, dan saya mendapatkan response invoice_url
https://checkout-staging.xendit.co/web/615086c53c7210028707ef28 , dari url
tersebut ketika saya buka di browser, masih harus memilih metode
pembayaran. Apakah bisa langsung terpilih metode pembayarannya via API ?

Berikut saya cantumkan code  nodejs saya

const amount = 40000; // total tagihan
let item_details = []; // untuk membuat item tagihan
doc.data().items.forEach(item => {
item_details.push({
quantity:1,
price:40000,
name:"tagihan"
});
});

const arrMetode = new Array("BRI"); // array metode pembayaran berisi BRI,
MANDIRI, BCA, tergantung metode pembayaran yang dipilih
var parameter = {
externalID:external_id_xendit,
amount:amount,
invoiceDuration:3600,
payment_methods:arrMetode,
items:item_details
}

i.createInvoice(parameter)
.then(async (r) => {

let result = {
token: r.id,
redirect_url: r.invoice_url
}
return resolve(result);
});

Terima Kasih,
Hakim Asmui


Pada tanggal Sen, 27 Sep 2021 pukul 12.28 Luminto ***@***.***>
menulis:

**Comment by luminto17** [comment]
selamat malam @hakimasmui , untuk Invoice Xendit, saat ini tidak dapat terpilih langsung metode pembayaran nya ya Pak, dikarenakan Invoice Xendit ditujukan untuk menampilkan beragam metode pembayaran ke customer customer merchant untuk memilih metode pembayaran yang hendak digunakan.

Namun, metode pembayaran Invoice dapat di konfigurasi melalui Dashboard Xendit atau melalui API secara dinamis ya. Konfigurasi yang kami maksud adalah, contoh, apabila Pak Hakim hanya ingin menampilkan BNI VA dan tidak menampilkan BCA atau Mandiri VA, Pak Hakim dapat melakukannya dengan mudah melalui Dashboard dengan membuang centang pada metode pembayaran yang tidak diinginkan. Untuk API, bisa request value hanya `BRI` saja pada parameter `payment_methods`.

Dengan begitu, Invoice akan dibuat dengan metode pembayaran yang telah dikonfigurasi oleh merchant. Apakah menjawab Pak Hakim? Atau apakah boleh dijelaskan kebutuhannya untuk melakukan seleksi pembayaran langsung pada saat pembukaan Invoice?

**Comment by hakimasmui** [comment]
Dear Tim Xendit.

Saya masih belum paham mengenai api secara dinamis untuk payment_method
kegunaan nya seperti bagaimana ya ? Apakah kalau saya mengisi parameter
payment_methods hanya BRI maka merchant saya hanya bisa membayar lewat BRI
va atau bagaimana ?

Di aplikasi saya, saya sudah menyediakan metode pembayaran, jadi waktu
merchant saya sudah memilih metode pembayaran agar tidak memilih lagi waktu
membuka invoice_url dari Xendit.

Pada tanggal Sen, 27 Sep 2021 21.23, Luminto ***@***.***>
menulis:

**Comment by luminto17** [comment]
Selamat pagi @hakimasmui , terima kasih atas pertanyaannya

Bener pak, apabila `payment_methods` diisi dengan `["BRI"]`, maka Invoice hanya akan menunjukkan BRI VA. Apabila `payment_methods` diisi dengan `["BRI", "MANDIRI"], maka Invoice akan menunjukkan BRI dan Mandiri VA

Baik, apabila user Bapak memilih metode pembayaran di aplikasi, Bapak bisa menggunakan API server-to-server seperti [Buat VA](https://developers.xendit.co/api-reference/id/#buat-virtual-account), sehingga ketika user telah memilih metode pembayaran, aplikasi Bapak akan request ke API [Buat VA](https://developers.xendit.co/api-reference/id/#buat-virtual-account) dengan parameter yang tersedia disana

Sebagai tambahan konteks:

- API Invoice adalah API untuk menampilkan metode pembayaran dimana UI nya di buat oleh Xendit (bisa di cek UI nya disini https://demo.xendit.co/), yang cocok bagi pengguna yang ingin menggunakan UI Xendit atau menghemat biaya pembuatan UI
- API VA adalah API untuk membuat Virtual Account yang cocok untuk pengguna yang memiliki UI pembayaran sendiri, sehingga API ini hanya akan membuat dan menjalankan pembayaran dari back-end tanpa UI

Semoga menjawab ya Pak
