### ISSUE TITLE
Add missing recurring payment properties

### ISSUE THREAD

**Issue by kenzojrc** [xendit/xendit-node#116]
https://developers.xendit.co/api-reference/#create-a-recurring-payment

The recurring payment `createPayment` method does not accept `customer`, `customer_notification_preference` as properties. 

The `payerEmail` property is required instead of optional.

The recurring payment module does not seem to be updated with the current API.

**Comment by bob-xendit** [comment]
Hi @kenzojrc

Thanks for the recommendation, we have applied the suggestion at below release.
https://github.com/xendit/xendit-node/releases/tag/v1.18.0

**Comment by kenzojrc** [comment]
Hi @bob-xendit, thank you! Can the new release be published to npm as well? 

Much appreciated!

**Comment by xen-HendryZheng** [comment]
Hi @kenzojrc We've updated at npm as well as per requested.
![image](https://user-images.githubusercontent.com/90175540/140297442-1b6638a7-e68a-409d-bba0-a22f66bfccb0.png)
Thanks !
