### ISSUE TITLE
QR_CODE metadata:null

### ISSUE THREAD

**Issue by ekibagascan** [xendit/xendit-node#119]
Halo perkenalkan saya Bagas, saya saat ini sedang integrasi Xendit untuk payment QRIS, tetapi saya tidak bisa POST metadata melalui server saya, hasilnya selalu null, sedangkan saat saya coba langsung dengan postman di https://api.xendit.co/qr_codes bisa.

### **Berikut payload saya:**

{
	"external_id": "testing_id_{{$timestamp}}",
	"type": "DYNAMIC",
	"callback_url": "https://ff2e-182-1-76-219.ngrok.io/api/transactions/callback/status",
	"amount": 2000,
    "metadata": {
     "playerId": "324254345345",
     "productName": "1B Diamond",
     "totalPrice": "50000",
     "productId": "1234324343",
     "paymentMethod": "Qris",
     "category": "Free Fire",
     "emailorPhone": "+6288803890773"
    }
}

### **Response**

created QR code {
  id: 'qr_ffaac6f6-250f-496a-94df-b89ea1eb6637',
  external_id: 'testing_id_1637111843',
  amount: 2000,
  description: '',
  qr_string: 'mock-QR-string-use-simulate-payment-to-test-flow',
  callback_url: 'https://ff2e-182-1-76-219.ngrok.io/api/transactions/callback/status',
  type: 'DYNAMIC',
  status: 'ACTIVE',
  created: '2021-11-17T01:17:22.873Z',
  updated: '2021-11-17T01:17:22.873Z',
  metadata: null
}

### **Berikut adalah code saya**

![mycode_qris](https://user-images.githubusercontent.com/41675517/142092265-fe2d02c0-5885-4ddd-9a9a-2cfbc3c67413.png)

### **Dan ini respon ketika saya coba direct ke xendit url tanpa Post ke server saya**

![qris test](https://user-images.githubusercontent.com/41675517/142092343-fb125f50-f326-4910-9c94-6df4db6096a6.png)

**Comment by xen-HendryZheng** [comment]
Hi @ekibagascan kita udah release v1.19.0 ya utk issue ini. Mungkin boleh di coba lagi :)
