### ISSUE TITLE
Create Customer validation error 400, message "There was an error with the format submitted to the server."

### ISSUE THREAD

**Issue by denialfarizi1** [xendit/xendit-node#123]
ketika menambahkan customer baru selalu terdapat eror 400, 
misal format yang dikirim 
   {
                        referenceID:'demo_1475801962607',
                        givenNames: 'John',
                        mobileNumber: '+628324234324',
                        email: 'denialfarizi@gmail.com',
                  }
response server selalu muncul 
    "statusCode": 400,
    "message": "There was an error with the format submitted to the server.",
    "status": 400,
    "code": "API_VALIDATION_ERROR"
  }
    padahal sudah mengikuti setandar format parameter yang diberikan , saya pikir format ini masih menggunakan standar api xendit versi 1 bukan yang terbaru mohon diupdate dan mohon pencerahannya

**Comment by luminto17** [comment]
Selamat siang @denialfarizi1 ,

Setelah saya melakukan pengecekan menggunakan data yang terlampir, saya tidak menemukan error tersebut

Apakah boleh diinformasikan request payload (body dan header) nya untuk kami bantu cek lebih lanjut?
Dan apakah ada response array `errors` yang menunjukkan lokasi kesalahan pada message nya?

**Comment by denialfarizi1** [comment]
Saya mengikuti example tautan ini
https://github.com/xendit/xendit-node/blob/master/examples/with_promises/customer.js
dengan request paramter customer
referenceID: new Date().toISOString(),
  givenNames: 'customer 1',
  email: 'customer@website.com',
  mobileNumber: '+6281212345678',
  description: 'dummy customer',
  middleName: 'middle',
  surname: 'surname',
  addresses: [],

akhirnya mendapatkan error message seperti ini
{
  "error": {
    "statusCode": 400,
    "message": "There was an error with the format submitted to the server.",
    "status": 400,
    "code": "API_VALIDATION_ERROR"
  }
}
adakah solusi lain ?

**Comment by najibuhuy** [comment]
It seems like apiVersion is required, when I add apiVersion: '2020-05-19', this error disappeared. Thanks.

**Comment by arthu9** [comment]
Good Day! 

I have the same issue and already added apiVersion: '2020-05-19' but the still got 

{
    "error_code": "API_VALIDATION_ERROR",
    "message": "There was an error with the format submitted to the server.",
    "errors": [
        {
            "message": "\"client_reference\" is required",
            "path": [
                "body",
                "client_reference"
            ],
            "type": "any.required",
            "context": {
                "key": "client_reference",
                "label": "client_reference"
            }
        }
    ]
}

I would appreciate the help. Thank you.

**Comment by svashish305** [comment]
Hi is this fixed? I'm also getting the same error on latest SDK

**Comment by Pratyum** [comment]
Your API Version here is `apiVersion: '2020-15-19',` but it should be `apiVersion: '2020-*0*5-19',`

**Comment by adityarx** [comment]
Closing this issue as answered, thanks!
