### ISSUE TITLE
CORS error on using this https://api.xendit.co/ewallets/charges

### ISSUE THREAD

**Issue by Kimmydoray** [xendit/xendit-node#152]
Here's my code:
         

            const resp = await ew.createEWalletCharge({
                referenceID: 'test-reference-id',
                currency: 'PHP',
                amount: 1000,
                checkoutMethod: 'ONE_TIME_PAYMENT',
                channelCode: 'PH_GCASH',
                channelProperties: {
                    successRedirectURL: 'http://localhost:8000',
                },
                metadata: {
                    branch_code: 'tree_branch'
                }
            });
            console.log(resp);

but it always showing this error once I fire the function at the top, need answers please and thank you.

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/44127458/161389105-72b56533-c322-44b9-8fda-868720741065.png">

**Comment by MESMUR** [comment]
This is a CORS error not an SDK issue. Please read up on CORS, the Xendit API doesn't allow requests from browser like environments.

Here's a similar issue you can read up on: [Stackoverflow Issue](https://stackoverflow.com/questions/53684484/posting-to-external-api-throws-cors-but-it-works-from-postman)

**Comment by Kimmydoray** [comment]
Good day,

Thank you for your response, I would like to know what is the best solution
for this issue, cause the idea is once the user click the "Pay" button the
api request will fire.

Thank you,
Edzel

**Comment by Kimmydoray** [comment]
Cause it is so weird that they created api for it then they don't allow
browser to send request?

**Comment by MESMUR** [comment]
You'll have to do more research to figure this out, but it looks like this is a vue frontend.
You can try routing this request through a server you've created.
vue frontend -> node backend -> api request to Xendit

There might be a better way to go about it, CORS is standard, it's not just for the Xendit API.

**Comment by Kimmydoray** [comment]
Good day Maahir,

Yeah, that is what I did instead of triggering the request thru front end I
just trigger it on my backend laravel.
Thank you for your response.

**Comment by MESMUR** [comment]
Glad to hear that, I'll be closing the issue now.

**Comment by Kimmydoray** [comment]
Thanks I also follow you on linked, your the best <3
