### ISSUE TITLE
For User Id

### ISSUE THREAD

**Issue by zainiazhr14** [xendit/xendit-node#167]
Where i can get for-user-id in xendit dashboard.

**Comment by luminto17** [comment]
Hi @zainiazhr14 , great question. You can visit our Dashboard --> XenPlatform --> Accounts. Documentation here https://docs.xendit.co/xenplatform/dashboard for reference

Hope it helps~

**Comment by zainiazhr14** [comment]
because in xenPlatform doesn't exist any menus
