### ISSUE TITLE
API Key is Invalid in test Mode

### ISSUE THREAD

**Issue by stanley355** [xendit/xendit-node#168]
Hi I'm working on Xendit-node to create an invoice, I've made my Xendit account (still in test mode), and generated my API Key (`xnd_public_development_xxxxx`).
I've ensured that I've set my `money-in` to write however it still gives me this error `The API key provided is invalid. Please make sure to use the secret/public API key that you can obtain from the Xendit Dashboard`.

My question will be does API Key not working in `test mode` so I should activate my account in order to start using my API Key?
Thanks

**Comment by MESMUR** [comment]
You seem to be using your public API Key from here: 
This is only meant for some of the Xendit Card APIs
![image](https://user-images.githubusercontent.com/22883661/195034046-0b9716bb-d43e-4255-9b32-ccc04d831503.png)

For the secret API Key, when you create one, you should find it in this box: 
![image](https://user-images.githubusercontent.com/22883661/195034268-103c37df-b6b9-4e3f-8e98-dc15848b1d2d.png)

Please use this API key.

**Comment by stanley355** [comment]
Ah Got it thanks!
