### ISSUE TITLE
Need to add forUserId for Transactions & Reports API

### ISSUE THREAD

**Issue by rifkyanzar** [xendit/xendit-node#178]
Hi guys, I think forUserId headers for Transactions & Reports API need to be added.

 #179 

Thank you.

**Comment by adityarx** [comment]
Hello @rifkyanzar, this is a little bit late, but we really appreciate your PR to add this to our SDK. I have left a comment on the PR if you're still interested in having this merged and released

**Comment by adityarx** [comment]
Closing this as inactive, feel free to open it again if you'd like us to take a look at the PR
