### ISSUE TITLE
PH_GCASH and PH_GRABPAY is not included in the ChannelCode Type for Creating Ewallet Charge

### ISSUE THREAD

**Issue by schindlerwork** [xendit/xendit-node#182]
Good Day,

I noticed that the ChannelCode type in Create EWallet Charge doesn't include PH_GCASH and PH_GRABPAY. It only includes PH_PAYMAYA for Philippines Ewallets.

![image](https://user-images.githubusercontent.com/105701674/210720760-f3e67300-1931-41b5-87e1-28eac6086063.png)

![image](https://user-images.githubusercontent.com/105701674/210720890-a9eae8b2-88b1-4a07-bee0-a360bfc79888.png)

That is why I am currently importing the package using the require keyword because when I import it using the import keyword, I cannot pick PH_GCASH and PH_GRABPAY because it is not included in the ChannelCode Types for creating ewallet charges.

By importing using the require keyword, it works. But I wanted to utilize the package types.

Hoping to get a reply from you soon.

**Comment by adityarx** [comment]
@schindlerwork our team is capacity constrained at the moment, and are unable to assist with adding this at the moment. If you're able to provide a PR adding this change, we're happy to review it 🙏
