### ISSUE TITLE
Basic Auth 'INVALID_API_KEY'

### ISSUE THREAD

**Issue by MaximusDeFlorenzo** [xendit/xendit-node#191]
when i was working out on xendit, i want to get a balance data on testing side but there's an error, i was struggle to find the answer, the error is 'No API Key detected. Please provide your API key in the Authorization header, using Basic auth (e.g. "Authorization: Basic YOUR_SECRET_KEY"). See https://developers.xendit.co/api-reference/#authentication for details'

my code:
![Screenshot (199)](https://user-images.githubusercontent.com/86521887/234837770-a22e8503-b342-417e-a038-7e26bdf37982.png)

**Comment by adityarx** [comment]
Hello @MaximusDeFlorenzo, we're sorry you ran into this issue. We're keeping issues on GitHub reserved for active bugs and feature requests for our Node SDK, so we encourage you to have a look at our Docs (https://docs.xendit.co/) or ask for help through the chatbot. Cheers and sorry we couldn't be of help~
