### ISSUE TITLE
data.expirationDate.toISOString is not a function

### ISSUE THREAD

**Issue by diarmp** [xendit/xendit-node#192]
in va after I add expirationDate,

i got error : data.expirationDate.toISOString is not a function.

please remove .toISOString

or fix it with add moment js

thanks

Diar

**Comment by adityarx** [comment]
@diarmp toISOString() is a [valid JS method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) so I don't think this might be the issue. For implementation related assistance, we suggest you reach out for help through the contact page (https://www.xendit.co/en/contact/) thanks!

**Comment by adityarx** [comment]
Closing this issue, please re-raise if its still an issue! Happy to chat further
