### ISSUE TITLE
Error 418 createBatch Disbursement

### ISSUE THREAD

**Issue by cyber12341** [xendit/xendit-node#196]
hi xendit team,
i get error 418 when trying to createBatch disbursement

const x = new xendit({ secretKey: APIKEY });
    const { Disbursement } = x
    const disbursement = new Disbursement({});

    const resp = new disbursement.createBatch({
      reference: "1683720000011",
      disbursements: [
        {
            "externalID": "1685346712780273",
            "bankCode": "BCA",
            "accountHolderName": "Stanley Nguyen",
            "accountNumber": "9999415486",
            "description": "Reumbursement dari Invoice INVSPA0004CSA000123052301",
            "amount": 30000
        },
        {
            "externalID": "1685344714429815",
            "bankCode": "MANDIRI",
            "accountHolderName": "Duopomelo",
            "accountNumber": "9999049407",
            "description": "Reumbursement dari Invoice INVSPA0004CSA000123052301",
            "amount": 50000
        }
    ],
    })

response 
`{
status: 418,
code: 'JS_ERROR',
message: "Cannot read properties of undefined (reading 'secretKey')"
}`

**Comment by adityarx** [comment]
Hi @cyber12341, we'll need to see your initialization code to help with this. However, for better support, it would be recommended to reach out via our help page [here](https://www.xendit.co/en/contact/)

**Comment by adityarx** [comment]
Closing this as inactive
