### ISSUE TITLE
Where to put for-user-id header parameter in createInvoice?

### ISSUE THREAD

**Issue by rainerregan** [xendit/xendit-node#208]
I have searched through the sourcecode, but I still haven't found how to put the for-user-id header parameter when creating an Invoice.

https://developers.xendit.co/api-reference/?bash#create-invoice

**Comment by adityarx** [comment]
Hi @rainerregan, unfortunately `for-user-id` and XenPlatform support isn't available just yet. But we are working towards adding this to our SDKs. If you could raise your request to your Account or Sales Manager, we'd be happy to talk further.
