### ISSUE TITLE
Feature Request: `with-fee-rule` support for Payment Request API

### ISSUE THREAD

**Issue by khairul169** [xendit/xendit-node#210]
I don't know if this is only related to xendit node library or not, but it appears that the [Payment Request API](https://developers.xendit.co/api-reference/payments-api/#create-payment-request) currently doesn't have support for xenPlatform's `with-fee-rule` options.

This would be good if this feature were implemented in the Payments API, instead of using each channels API.

**Comment by adityarx** [comment]
Agreed @khairul169, this is on our roadmap at the moment. I can't give you an exact ETA at the moment but we should be able to add this to Payments API as well as to the SDK in about 1-3 months 🙏

**Comment by billgun** [comment]
Is there any update to this?

**Comment by khairul169** [comment]
> Is there any update to this?

It is supported now, you can use `with-split-rule` header as a replacement from the older `with-fee-rule` feature.
