### ISSUE TITLE
Xendit v2 new payout method

### ISSUE THREAD

**Issue by Peepersoak** [xendit/xendit-node#215]
Hi,

I just updated my app to use the latest version and when it comes to the payout method, is there a way to change the direct disbursement of the payout method?

Currently, with this, the transaction will be made automatically without approving it but what I need is to manually approve them in the Xendit dashboard under the disbursement section. I'm trying to find this in the documentation but I can't seem to find it. I have this setup in the previous version so I would like to keep it that way with manually approving the disbursement

**Comment by adityarx** [comment]
Hi @Peepersoak, if you need manual approval, our team recommends using the Batch Disbursement API. This currently isn't on the SDK and our team aren't planning to add it soon. We recommend integrating via the API for now, but do escalate this to your Account Manager if you would like another soluition!
