### ISSUE TITLE
The expression of an export assignment must be an identifier or qualified name in an ambient context.

### ISSUE THREAD

**Issue by ardyfeb** [xendit/xendit-node#40]
According https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#arbitrary-expressions-are-forbidden-in-export-assignments-in-ambient-contexts exporting ambient contexts are forbidden

exportig definition should be:
```
class Xendit {
    ...
}

export = Xendit
```
instead export directly:
```
export = class Xendit {
  ...
}
```

so we must refactoring https://github.com/xendit/xendit-node/blob/master/src/xendit.d.ts and related files

**Comment by stanleynguyen** [comment]
@ardyfeb I wonder if it's a problem though 🤔 because we have already given an identifier `Xendit` to the class, just exporting with shorthand instead of exporting on a separate line.
Would really appreciate it if you can provide a code example for bug reproduction 😄

**Comment by huben92** [comment]
it is a problem, we need to downgrade typescript to below 2.6 if want to use xendit-node on our project.
Please fix it.

**Comment by stanleynguyen** [comment]
Hey @huben92 would you like to take this up and get it fixed immediately?

**Comment by huben92** [comment]
Yes, sure
