### ISSUE TITLE
Ewallet Response Error Code

### ISSUE THREAD

**Issue by simpelin** [xendit/xendit-node#44]
How to get Response error Code Ewallet OVO and Dana by PHP Script.

I received a response type string.

I try :

Param :
`$data               = [
            'external_id'   => $Code,
            'amount'        => $Amount,
            'phone'         => '0' . $phone,
            'ewallet_type'  => $PaymentMethod
        ];
`

        try{
            $Result = EWallets::create($data);
        }catch (\ ApiExceptions $apiExceptions){
          // Condition A //
            $Data                       = [
                'status'                => false,
                'message'               => $apiExceptions->getMessage(),
                'code'                  => $apiExceptions->getCode()
            ];

            return response($Data, 200)
                ->header('Content-Type', 'text/plain');

        }catch (\ Exception $exception){
          // Condition B //
            $Data                       = [
                'status'                => false,
                'message'               => $exception->getMessage(),
                'code'                  => $exception->getCode()
            ];

            return response($Data, 200)
                ->header('Content-Type', 'text/plain');
        }

**Respons condition B**

<img width="236" alt="Screen Shot 2020-02-28 at 16 08 30" src="https://user-images.githubusercontent.com/61580767/75529887-30228280-5a46-11ea-81ca-99c7e079a53d.png">
<img width="456" alt="Screen Shot 2020-02-28 at 16 08 46" src="https://user-images.githubusercontent.com/61580767/75529943-344ea000-5a46-11ea-9607-3534511d4880.png">

**Comment by stanleynguyen** [comment]
Issue opened in https://github.com/xendit/xendit-php/issues/58 and will be handled there. Closing this as it's not relevant to `xendit-node`
