### ISSUE TITLE
INSTALASI SUKSES TP PHP EROR

### ISSUE THREAD

**Issue by stevanhoo** [xendit/xendit-node#52]
saya sudah install dengan composer dan muncul folder vendor

lalu next stepnya, saya buka di localhost 
http://localhost/xendit/vendor/xendit/xendit-php/tests/TestCase.php

keluar eror
Fatal error: Uncaught Error: Class 'PHPUnit\Framework\TestCase' not found in C:\xampp\htdocs\xendit\vendor\xendit\xendit-php\tests\TestCase.php:25 Stack trace: #0 {main} thrown in C:\xampp\htdocs\xendit\vendor\xendit\xendit-php\tests\TestCase.php on line 25

boleh tolong ??

**Comment by mychaelgo** [comment]
hi @stevanhoo , untuk xendit-php, bisa  buka issuenya di https://github.com/xendit/xendit-php/issues/new ?

**Comment by stanleynguyen** [comment]
Closing as it's not `xendit-node` related
