### ISSUE TITLE
Integrate With Angular

### ISSUE THREAD

**Issue by kotekaweb** [xendit/xendit-node#57]
Is it possible to integrate with Angular? I try to integrate API with angular HTTP but always response error CORS. Any solution about this ?

**Comment by stanleynguyen** [comment]
Hi @kotekaweb, you have to access our API from a secure backend

**Comment by stanleynguyen** [comment]
Putting your secret api key in your frontend code is a security risk

**Comment by kotekaweb** [comment]
is there any example how to do it ?

**Comment by stanleynguyen** [comment]
We don't have any tutorials yet but you can probably follow this series to build a web server https://dev.to/miku86/what-is-nodejs-how-to-install-it-1900
