### ISSUE TITLE
getaddrinfo EAI_AGAIN api.xendit.co:443

### ISSUE THREAD

**Issue by kotekaweb** [xendit/xendit-node#58]
I try to get Balance, but get response like this : 

{
message: "request to https://api.xendit.co/balance failed, reason: getaddrinfo EAI_AGAIN api.xendit.co:443",
type: "system",
errno: "EAI_AGAIN",
code: "EAI_AGAIN"
}

**Comment by stanleynguyen** [comment]
Looks like you had a network issue. I suggest just restarting your network and try again

**Comment by stanleynguyen** [comment]
Stale
