### ISSUE TITLE
docs: change EWallet.Type.DANA to EWallet.Type.Dana

### ISSUE THREAD

**Issue by burhanahmeed** [xendit/xendit-node#71]
I guess there is something wrong in the[ ewallet docs.](https://developers.xendit.co/api-reference/?javascript#create-payment) In the docs, the  ewallet_type for dana it's written like `EWallet.Type.DANA`, but it always return error `400 API_VALIDATION_ERROR`
<img width="597" alt="Screenshot 2021-01-29 at 16 56 48" src="https://user-images.githubusercontent.com/19145812/106265561-d039ea80-6259-11eb-86c9-e880d1aa708a.png">

when I changed it to `EWallet.Type.Dana` and it is working now.

**Comment by stanleynguyen** [comment]
Hi @burhanahmeed you might want to check your text editor auto-complete. We have declared the enum here to be followed
https://github.com/xendit/xendit-node/blob/591b14e697747049760db6239aa80900a4db4ee2/src/ewallet/ewallet.d.ts#L3-L7
