### ISSUE TITLE
createRefund Api error not fixing

### ISSUE THREAD

**Issue by RanaNasir018** [xendit/xendit-node#75]
when i am getting charge with with id retrieved from createCharge endpoint it is giving me success. But when i am using same id in refundCharge it is giving me error credit card charge not found please guide me this

**Comment by stanleynguyen** [comment]
@RanaNasir018 would you mind attaching your snippet of code here?

**Comment by luminto17** [comment]
stale. closing issue, but feel free to reopen with additional information regarding the issue
