### ISSUE TITLE
EWallet.createPayment() vs EWallet.createEWalletCharge()

### ISSUE THREAD

**Issue by hanprat** [xendit/xendit-node#80]
What is the difference between `EWallet.createPayment()` and `EWallet.createEWalletCharge()`? 

I've try DANA with `createPayment()` and with `createEWalletCharge()` too. Both have different flow.
Using `createPayment()`, I can test with the "real" flow (pages in DANA for topup). But, using `createEWalletCharge()` the url-redirection is just a simple page with button "Proceed to pay" and when it's clicked saying something like "test is done".
Is it supposed to be different in testing?

With `createPayment()` I can set the callback url, but where to set the callback url when using `createEWalletCharge()`?

**Comment by luminto17** [comment]
hi @hanprat , great questions
- `EWallet.createPayment()` is our old eWallet API we built back in 2019 https://developers.xendit.co/api-reference/ewallets/create-payment/#2020-02-01, in which only support `OVO`, LinkAja`, and `DANA`
- `EWallet.createEWalletCharge()` is the latest eWallet API we built. We solve bunch of inconsistencies and we add most requested channels by our customers here in this API such as `Shopeepay` (Indonesia) and `Paymaya`, `Gcash`, `Grabpay` (Philippines)

Our official recommendations:
- Use `EWallet.createEWalletCharge()` to future-proof your integration. Future ewallets features will only be available in `EWallet.createEWalletCharge()`
- Setup callback URL via Dashboard https://docs.xendit.co/api-integration/callback/setup

Glad you ask to clarify. Teaser: Our ewallet is planning to drop support safely for `EWallet.createPayment()`. As soon as they have published the deprecation plan, we'll add the deprecation note here for discoverability

Let me know if this answer your questions or not :)

**Comment by hanprat** [comment]
thanks @luminto17 for the explanation.

I can see why the readme change from `createPayment()` to `createEWalletCharge()`. Was using `createPayment()` for several months, and last few days can't find the doc/reference.

**Comment by hanprat** [comment]
Hi, @luminto17 
In testing-mode, does your system still hit the callback URL for ewallet charge?

**Comment by luminto17** [comment]
hi @hanprat absolutely, you can test negative scenarios here using these input https://docs.xendit.co/ewallet/integrations/test-scenarios
