### ISSUE TITLE
Xendit.js 404

### ISSUE THREAD

**Issue by iwgx** [xendit/xendit-node#81]
`Xendit.js` link in README navigate to 404 page, is it expected?

![Screenshot 2021-03-23 191714](https://user-images.githubusercontent.com/20817629/112145118-8e4f7400-8c0c-11eb-8966-4a1ba8954339.png)

**Comment by luminto17** [comment]
hi @iwgx thanks for reporting! but the page is still available but we shortened previous link. You can find the Xendit.js documentation here https://docs.xendit.co/credit-cards/integrations/tokenization

I'll change the Readme to adjust to the new link to Xendit Docs

**Comment by luminto17** [comment]
https://github.com/xendit/xendit-node/pull/82

**Comment by stanleynguyen** [comment]
Resolved in #82
