### ISSUE TITLE
[new] Tokenization for ewallet

### ISSUE THREAD

**Issue by kneric** [xendit/xendit-node#85]
this issue raised to ask for support tokenization flow for ewallet. we'll need Initialize Linked Account Tokenization method to be able to pass in cancel_redirect_url

**Comment by luminto17** [comment]
Hi @kneric, we have just released ewallet tokenization support in v1.19.4 https://github.com/xendit/xendit-node/releases/tag/v1.19.4

Kindly check it out and let us know if any feedback
