### ISSUE TITLE
[Feature Request] Typescript Code Completion

### ISSUE THREAD

**Issue by excalios** [xendit/xendit-node#87]
In the current state of typescript support, it doesn't show any suggestion for typescript which is definitely not a huge problem but I think it would be very helpful.
![image](https://user-images.githubusercontent.com/42968441/119380817-a5394200-bcf3-11eb-9b4e-fc3dde367f0e.png)
Besides, there's no actual type besides for the xendit class and xendit opts for initialization. There no invoice type, card type, etc even though from looking at the code the types actually exist it's not detected.
In javascript the suggestion still exist of course
![image](https://user-images.githubusercontent.com/42968441/119383477-f6e2cc00-bcf5-11eb-9189-b43ae904d52e.png)

**Comment by stanleynguyen** [comment]
Thanks @excalios for raising this. It might have something to do with our type definition files. We will check and fix them as soon as we can.

**Comment by stanleynguyen** [comment]
Hey @excalios, I can't seem to replicate the issue
![Screenshot 2021-06-10 at 16 42 37](https://user-images.githubusercontent.com/12974927/121494143-0e66c800-ca0b-11eb-887b-50bd1abf2c6f.png)

Could you share with us what the editor you are using, its version, and the syntax-highlighting/code-completing extension that you're using?

**Comment by excalios** [comment]
Hello @stanleynguyen ,
On the screenshot it was on
OS: Fedora Workstation 32
Editor:Neovim with CoC

I also tried it on vs code it has the same result
I also tried in my windows using vs code and it is also the same

From your screenshot it looks like Javascript? Just making sure because on Javascript it's totally fine on me. On typescript it doesn't show anything.

**Comment by stanleynguyen** [comment]
> Hello @stanleynguyen ,
> On the screenshot it was on
> OS: Fedora Workstation 32
> Editor:Neovim with CoC
> 
> I also tried it on vs code it has the same result
> I also tried in my windows using vs code and it is also the same
> 
> From your screenshot it looks like Javascript? Just making sure because on Javascript it's totally fine on me. On typescript it doesn't show anything.

oh got it thanks @excalios . We're fixing it
