### ISSUE TITLE
 Add new optional param for invoice creation

### ISSUE THREAD

**Issue by wildan3105** [xendit/xendit-node#88]
New param with type `string` and name: `reminder_time_unit`

**Comment by dharmasatrya** [comment]
https://github.com/xendit/xendit-node/pull/126

**Comment by luminto17** [comment]
Hi @wildan3105 , we have released your request in this v1.19.2 https://github.com/xendit/xendit-node/releases/tag/v1.19.2. Kindly check it out when you have the chance. Thank you
