### ISSUE TITLE
Error expiration date when update Virtual Account

### ISSUE THREAD

**Issue by ramawidi** [xendit/xendit-node#93]
Hi, I just face a problem when I update my virtual account for expiration date. Here's my line of code when requesting for updating my virtual account.

` const resp = await va.updateFixedVA({
        id: <my_id>,
        expectedAmt: 10000,
        expirationDate: "2040-12-31T17:00:00.000Z"
      });
`

But get a message "data.expirationDate.toISOString is not a function". Any help please?

**Comment by ramawidi** [comment]
Here's the response what I got

<img width="1051" alt="Screen Shot 2021-06-17 at 19 02 43" src="https://user-images.githubusercontent.com/11472261/122393165-c9104080-cf9e-11eb-8afb-0294ccbfa796.png">

**Comment by ErvanAdetya** [comment]
@ramawidi the `expirationDate` is using date not string.

to fix
`const resp = await va.updateFixedVA({ id: <my_id>, expectedAmt: 10000, expirationDate: new Date("2040-12-31T17:00:00.000Z") });`

Let me know if it's not working

**Comment by ramawidi** [comment]
Oh sorry, that's my lack of undestanding on it. Thank you for your reply. I will try it. And close this. issue
