### ISSUE TITLE
Required channel properties missing for GCash and GrabPay

### ISSUE THREAD

**Issue by RamonMamon** [xendit/xendit-node#98]
![image](https://user-images.githubusercontent.com/35195972/126325083-a60cb07c-8fe7-4b41-9279-e767c222b067.png)
The ewallet channel properties are missing the required _failure_redirect_url_ field for both GCash and GrabPay.

**Comment by anthonyballugjr** [comment]
![image](https://user-images.githubusercontent.com/40159033/129695782-cc23f864-e85a-42cf-989a-2bbeaf8c5d2f.png)

I am having the same error, seems like other e-wallets are not configured yet.

**Comment by RamonMamon** [comment]
@anthonyballugjr I temporarily fixed the problem by just adding the missing _failure_redirect_url_ field manually under the _success_redirect_url_ field that you see in the image. Should work fine until they decide to release a patch.

**Comment by stanleynguyen** [comment]
Hey @anthonyballugjr @RamonMamon, it's been fixed in v1.15.0. Thanks for raising the issue
